server:
  port: 8082
spring:
  application:
    name: car-rental-service
  datasource:
    url: "jdbc:mysql://localhost:3306/udemy"
    username: root
    password: eric@2024
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
